import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import peggy from 'peggy';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(projectRoot, '..');

const grammarPath = path.join(repoRoot, 'grammar', 'ocs-t.peggy');
const outputDir = path.join(projectRoot, 'src', 'generated');
const outputFile = path.join(outputDir, 'ocs-t-parser.ts');

async function buildParser() {
  const grammar = await readFile(grammarPath, 'utf8');
  const source = peggy.generate(grammar, {
    output: 'source',
    format: 'es',
  });

  const banner = `// @ts-nocheck\n// This file is auto-generated by scripts/build-parser.js.\n// Do not edit this file directly.\n\n`;

  await mkdir(outputDir, { recursive: true });
  await writeFile(outputFile, `${banner}${source}`, 'utf8');
}

buildParser().catch((error) => {
  console.error(error);
  process.exit(1);
});
